[package]
name = "libmw"
version = "0.1.0"
authors = ["douglas"]
edition = "2018"

[dependencies]
jni = { version = "0.10.2", default-features = false }

[profile.release]
lto = true

[lib]
name = "mw"
crate-type = ["cdylib"]
